FROM nodered/node-red:3.0.0-14-minimal
RUN npm install node-red-dashboard \
    npm install node-red-contrib-influxdb \
    npm install node-red-node-random \
    npm install node-red-contrib-file-function \
    npm install node-red-contrib-mqtt-broker 